[book]
title = "Podigni kvalitet svog koda kao softverski inženjer"
description = "Zbirka lekcija i studija slučaja o unapređenju kvaliteta koda na srpskom jeziku"
language = "sr"
authors = ["Zanatlije Koda"]
multilingual = false
src = "src"
topics = ["Code Quality", "Best Practices", "Refactoring"]

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "rust"
fold.enable = true
smart-punctuation = true

